# Install ArgoCD on clusters that will use ArgoCD for management of GitOps
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-argocd-to-label-clusters
  namespace: argocd
spec:
  clusterSelector:
    matchLabels:
      gitops-mgmt: argocd
