# Install the Manuela Factory+Line applications on manuela=factory servers running ArgoCD
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-argocd-factory-to-label-clusters
  namespace: argocd
spec:
  clusterSelector:
    matchLabels:
      gitops-mgmt: argocd
      manuela: factory
