bases:
- git::https://github.com/css-qe/bp-gcp-deploy-4.8.git/profiles/production.gcp/00_install-config 

patches:
- install-config.patch.yaml

patchesJson6902:
- target:
    version: v1
    kind: InstallConfig
    name: cluster
  path: install-config.name.patch.yaml

transformers:
- site-config.yaml
