apiVersion: v1
kind: Namespace
metadata:
  name: baremetal-edge
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    vendor: auto-detect
    name: baremetal-edge
    gitops-mgmt: argocd
    manuela: factory
  name: baremetal-edge
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: baremetal-edge
  namespace: baremetal-edge
spec:
  clusterName: baremetal-edge
  clusterNamespace: baremetal-edge
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 2.0.0
