apiVersion: v1
kind: Namespace
metadata:
  name: staging-aws
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    vendor: auto-detect
    name: staging-aws
    gitops-mgmt: argocd
    manuela: factory
  name: staging-aws
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: staging-aws
  namespace: staging-aws
spec:
  clusterName: staging-aws
  clusterNamespace: staging-aws
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 2.0.0
